name: CI
on:
  push:

jobs:
  job-collector:
    runs-on: ubuntu-latest
    container:
      image: netpicker/crt
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Run job collector
        run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 collect-jobs --co -p comfy.automate --rootdir $PWD/jobs $PWD/jobs
